services:
  # Backend Application
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-services
    environment:
      NODE_ENV: staging
      PORT: 5001
      MONGODB_URI: mongodb://localhost:27017/interview-monitoring
      JWT_SECRET: your_jwt_secret_key
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5001:5001"
    expose:
      - 5001
    networks:
      - interviewnet

  # Frontend Application
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-services
    environment:
      NODE_ENV: staging
    ports:
      - "5173:5173"
    expose:
      - 5173
    networks:
      - interviewnet

networks:
  interviewnet:
    driver: bridge
